version: '3'
services:
  miniforge3:
    build: conda
    volumes:
      - shared:/app/shared
  jupyter:
    build: jupyter
    volumes:
      - shared:/app/shared
    ports:
      - "8888:8888"
    command: "start-notebook.sh --NotebookApp.token=''"
    depends_on:
      - miniforge3

volumes:
  shared: